name: Development Release

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: "Development Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Install Toolchain
        run: sudo apt-get -y install gcc-arm-none-eabi
      - name: Install Cppcheck
        run: sudo apt-get -y install cppcheck
      - name: Clone STM32CubeF1
        run: git clone https://github.com/STMicroelectronics/STM32CubeF1.git
      - name: Run Cppcheck
        run: STM32CUBE_PATH=./STM32CubeF1 make cppcheck
      - name: Build Firmware (STM32duino 0x8002000)
        run: |
          make clean && \
          STM32CUBE_PATH=./STM32CubeF1 FIRMWARE_ORIGIN=0x8002000 make && \
          mv bluepill-serial-monster.bin bluepill-serial-monster-stm32duino-0x8002000.bin &&\
          mv bluepill-serial-monster.hex bluepill-serial-monster-stm32duino-0x8002000.hex
      - name: Build Firmware (STM32duino 0x8005000)
        run: |
          make clean && \
          STM32CUBE_PATH=./STM32CubeF1 FIRMWARE_ORIGIN=0x8005000 make && \
          mv bluepill-serial-monster.bin bluepill-serial-monster-stm32duino-0x8005000.bin &&\
          mv bluepill-serial-monster.hex bluepill-serial-monster-stm32duino-0x8005000.hex
      - name: Build Firmware (Bare)
        run: make clean && STM32CUBE_PATH=./STM32CubeF1 make
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            README.md
            *.bin
            *.hex
            inf/*.inf
            inf/*.cat
